# Generated by Django 5.2.7 on 2025-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailybalance_paymentplan_paymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
