# Generated by Django 5.2.7 on 2025-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_total_money_customer_total_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='total_money',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_money',
        ),
        migrations.AddField(
            model_name='company',
            name='market_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='market_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
