# Generated by Django 5.2.7 on 2025-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_marketmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='reputation',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('bad', 'Bad')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='reputation_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_paid_30_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
