# Generated by Django 5.2.7 on 2025-10-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_total_debt_customer_total_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
