# Generated by Django 5.2.7 on 2025-10-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='market_money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_debt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='market_money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_debt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_paid_30_days',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
