# Generated by Django 5.2.7 on 2025-10-09 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_make_user_fields_non_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmoney',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_money', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='marketmoney',
            unique_together={('user',)},
        ),
    ]
