# Generated by Django 5.2.7 on 2025-10-12 16:07

import django.db.models.deletion
from django.db import migrations, models


def create_currencies(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    
    # Create default currencies
    currencies = [
        {'code': 'IQD', 'name': 'Iraqi Dinar', 'symbol': 'د.ع', 'exchange_rate_to_iqd': 1.0, 'is_active': True},
        {'code': 'USD', 'name': 'US Dollar', 'symbol': '$', 'exchange_rate_to_iqd': 1500.0, 'is_active': True},
        {'code': 'EUR', 'name': 'Euro', 'symbol': '€', 'exchange_rate_to_iqd': 1600.0, 'is_active': True},
        {'code': 'GBP', 'name': 'British Pound', 'symbol': '£', 'exchange_rate_to_iqd': 1900.0, 'is_active': True},
    ]
    
    for currency_data in currencies:
        Currency.objects.get_or_create(
            code=currency_data['code'],
            defaults=currency_data
        )


def reverse_create_currencies(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_shopmoney_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('IQD', 'Iraqi Dinar'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(default='$', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange_rate_to_iqd', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(create_currencies, reverse_create_currencies),
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
    ]
