[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py migrate --settings=backend.settings_production"]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
