[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
