[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --settings=backend.settings_production"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
