[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.railpack]
buildCommand = "pip install -r requirements.txt"