# Generated by Django 5.2.7 on 2025-10-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
