# Generated by Django 5.2.7 on 2025-10-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_company_market_money_alter_company_total_debt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('debt_created', 'Debt Created'), ('debt_updated', 'Debt Updated'), ('debt_deleted', 'Debt Deleted'), ('payment_made', 'Payment Made'), ('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('profile_deleted', 'Profile Deleted')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
