# Generated by Django 5.2.7 on 2025-10-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_shopmoney_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('IQD', 'Iraqi Dinar')], default='USD', max_length=3),
        ),
    ]
